// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: im_protobuf.proto

package protobuf

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 查询用户是否在线
type QueryUsersOnlineReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AppID         uint32                 `protobuf:"varint,1,opt,name=appID,proto3" json:"appID,omitempty"`  // AppID
	UserID        string                 `protobuf:"bytes,2,opt,name=userID,proto3" json:"userID,omitempty"` // 用户ID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryUsersOnlineReq) Reset() {
	*x = QueryUsersOnlineReq{}
	mi := &file_im_protobuf_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryUsersOnlineReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryUsersOnlineReq) ProtoMessage() {}

func (x *QueryUsersOnlineReq) ProtoReflect() protoreflect.Message {
	mi := &file_im_protobuf_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryUsersOnlineReq.ProtoReflect.Descriptor instead.
func (*QueryUsersOnlineReq) Descriptor() ([]byte, []int) {
	return file_im_protobuf_proto_rawDescGZIP(), []int{0}
}

func (x *QueryUsersOnlineReq) GetAppID() uint32 {
	if x != nil {
		return x.AppID
	}
	return 0
}

func (x *QueryUsersOnlineReq) GetUserID() string {
	if x != nil {
		return x.UserID
	}
	return ""
}

type QueryUsersOnlineRsp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RetCode       uint32                 `protobuf:"varint,1,opt,name=retCode,proto3" json:"retCode,omitempty"`
	ErrMsg        string                 `protobuf:"bytes,2,opt,name=errMsg,proto3" json:"errMsg,omitempty"`
	Online        bool                   `protobuf:"varint,3,opt,name=online,proto3" json:"online,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryUsersOnlineRsp) Reset() {
	*x = QueryUsersOnlineRsp{}
	mi := &file_im_protobuf_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryUsersOnlineRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryUsersOnlineRsp) ProtoMessage() {}

func (x *QueryUsersOnlineRsp) ProtoReflect() protoreflect.Message {
	mi := &file_im_protobuf_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryUsersOnlineRsp.ProtoReflect.Descriptor instead.
func (*QueryUsersOnlineRsp) Descriptor() ([]byte, []int) {
	return file_im_protobuf_proto_rawDescGZIP(), []int{1}
}

func (x *QueryUsersOnlineRsp) GetRetCode() uint32 {
	if x != nil {
		return x.RetCode
	}
	return 0
}

func (x *QueryUsersOnlineRsp) GetErrMsg() string {
	if x != nil {
		return x.ErrMsg
	}
	return ""
}

func (x *QueryUsersOnlineRsp) GetOnline() bool {
	if x != nil {
		return x.Online
	}
	return false
}

// 发送消息
type SendMsgReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Seq           string                 `protobuf:"bytes,1,opt,name=seq,proto3" json:"seq,omitempty"`                   // 序列号
	AppID         uint32                 `protobuf:"varint,2,opt,name=appID,proto3" json:"appID,omitempty"`              // appID/房间ID
	FromUserId    string                 `protobuf:"bytes,3,opt,name=fromUserId,proto3" json:"fromUserId,omitempty"`     // 来源userId
	Cms           string                 `protobuf:"bytes,4,opt,name=cms,proto3" json:"cms,omitempty"`                   // cms 动作: msg/enter/exit
	Type          string                 `protobuf:"bytes,5,opt,name=type,proto3" json:"type,omitempty"`                 // type 消息类型，默认是 text
	Msg           string                 `protobuf:"bytes,6,opt,name=msg,proto3" json:"msg,omitempty"`                   // msg
	IsLocal       bool                   `protobuf:"varint,7,opt,name=isLocal,proto3" json:"isLocal,omitempty"`          // 是否查询本机 acc内部调用为:true(本机查询不到即结束)
	TargetUserId  string                 `protobuf:"bytes,8,opt,name=targetUserId,proto3" json:"targetUserId,omitempty"` //  目标userId
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendMsgReq) Reset() {
	*x = SendMsgReq{}
	mi := &file_im_protobuf_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendMsgReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendMsgReq) ProtoMessage() {}

func (x *SendMsgReq) ProtoReflect() protoreflect.Message {
	mi := &file_im_protobuf_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendMsgReq.ProtoReflect.Descriptor instead.
func (*SendMsgReq) Descriptor() ([]byte, []int) {
	return file_im_protobuf_proto_rawDescGZIP(), []int{2}
}

func (x *SendMsgReq) GetSeq() string {
	if x != nil {
		return x.Seq
	}
	return ""
}

func (x *SendMsgReq) GetAppID() uint32 {
	if x != nil {
		return x.AppID
	}
	return 0
}

func (x *SendMsgReq) GetFromUserId() string {
	if x != nil {
		return x.FromUserId
	}
	return ""
}

func (x *SendMsgReq) GetCms() string {
	if x != nil {
		return x.Cms
	}
	return ""
}

func (x *SendMsgReq) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *SendMsgReq) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *SendMsgReq) GetIsLocal() bool {
	if x != nil {
		return x.IsLocal
	}
	return false
}

func (x *SendMsgReq) GetTargetUserId() string {
	if x != nil {
		return x.TargetUserId
	}
	return ""
}

type SendMsgRsp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RetCode       uint32                 `protobuf:"varint,1,opt,name=retCode,proto3" json:"retCode,omitempty"`
	ErrMsg        string                 `protobuf:"bytes,2,opt,name=errMsg,proto3" json:"errMsg,omitempty"`
	SendMsgID     string                 `protobuf:"bytes,3,opt,name=sendMsgID,proto3" json:"sendMsgID,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendMsgRsp) Reset() {
	*x = SendMsgRsp{}
	mi := &file_im_protobuf_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendMsgRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendMsgRsp) ProtoMessage() {}

func (x *SendMsgRsp) ProtoReflect() protoreflect.Message {
	mi := &file_im_protobuf_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendMsgRsp.ProtoReflect.Descriptor instead.
func (*SendMsgRsp) Descriptor() ([]byte, []int) {
	return file_im_protobuf_proto_rawDescGZIP(), []int{3}
}

func (x *SendMsgRsp) GetRetCode() uint32 {
	if x != nil {
		return x.RetCode
	}
	return 0
}

func (x *SendMsgRsp) GetErrMsg() string {
	if x != nil {
		return x.ErrMsg
	}
	return ""
}

func (x *SendMsgRsp) GetSendMsgID() string {
	if x != nil {
		return x.SendMsgID
	}
	return ""
}

// 给这台机器的房间内所有用户发送消息
type SendMsgAllReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Seq           string                 `protobuf:"bytes,1,opt,name=seq,proto3" json:"seq,omitempty"`       // 序列号
	AppID         uint32                 `protobuf:"varint,2,opt,name=appID,proto3" json:"appID,omitempty"`  // appID/房间ID
	UserID        string                 `protobuf:"bytes,3,opt,name=userID,proto3" json:"userID,omitempty"` // 不发送的用户ID
	Cms           string                 `protobuf:"bytes,4,opt,name=cms,proto3" json:"cms,omitempty"`       // cms 动作: msg/enter/exit
	Type          string                 `protobuf:"bytes,5,opt,name=type,proto3" json:"type,omitempty"`     // type 消息类型，默认是 text
	Msg           string                 `protobuf:"bytes,6,opt,name=msg,proto3" json:"msg,omitempty"`       // msg
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendMsgAllReq) Reset() {
	*x = SendMsgAllReq{}
	mi := &file_im_protobuf_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendMsgAllReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendMsgAllReq) ProtoMessage() {}

func (x *SendMsgAllReq) ProtoReflect() protoreflect.Message {
	mi := &file_im_protobuf_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendMsgAllReq.ProtoReflect.Descriptor instead.
func (*SendMsgAllReq) Descriptor() ([]byte, []int) {
	return file_im_protobuf_proto_rawDescGZIP(), []int{4}
}

func (x *SendMsgAllReq) GetSeq() string {
	if x != nil {
		return x.Seq
	}
	return ""
}

func (x *SendMsgAllReq) GetAppID() uint32 {
	if x != nil {
		return x.AppID
	}
	return 0
}

func (x *SendMsgAllReq) GetUserID() string {
	if x != nil {
		return x.UserID
	}
	return ""
}

func (x *SendMsgAllReq) GetCms() string {
	if x != nil {
		return x.Cms
	}
	return ""
}

func (x *SendMsgAllReq) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *SendMsgAllReq) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

type SendMsgAllRsp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RetCode       uint32                 `protobuf:"varint,1,opt,name=retCode,proto3" json:"retCode,omitempty"`
	ErrMsg        string                 `protobuf:"bytes,2,opt,name=errMsg,proto3" json:"errMsg,omitempty"`
	SendMsgID     string                 `protobuf:"bytes,3,opt,name=sendMsgID,proto3" json:"sendMsgID,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendMsgAllRsp) Reset() {
	*x = SendMsgAllRsp{}
	mi := &file_im_protobuf_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendMsgAllRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendMsgAllRsp) ProtoMessage() {}

func (x *SendMsgAllRsp) ProtoReflect() protoreflect.Message {
	mi := &file_im_protobuf_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendMsgAllRsp.ProtoReflect.Descriptor instead.
func (*SendMsgAllRsp) Descriptor() ([]byte, []int) {
	return file_im_protobuf_proto_rawDescGZIP(), []int{5}
}

func (x *SendMsgAllRsp) GetRetCode() uint32 {
	if x != nil {
		return x.RetCode
	}
	return 0
}

func (x *SendMsgAllRsp) GetErrMsg() string {
	if x != nil {
		return x.ErrMsg
	}
	return ""
}

func (x *SendMsgAllRsp) GetSendMsgID() string {
	if x != nil {
		return x.SendMsgID
	}
	return ""
}

// 获取用户列表
type GetUserListReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AppID         uint32                 `protobuf:"varint,1,opt,name=appID,proto3" json:"appID,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserListReq) Reset() {
	*x = GetUserListReq{}
	mi := &file_im_protobuf_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserListReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserListReq) ProtoMessage() {}

func (x *GetUserListReq) ProtoReflect() protoreflect.Message {
	mi := &file_im_protobuf_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserListReq.ProtoReflect.Descriptor instead.
func (*GetUserListReq) Descriptor() ([]byte, []int) {
	return file_im_protobuf_proto_rawDescGZIP(), []int{6}
}

func (x *GetUserListReq) GetAppID() uint32 {
	if x != nil {
		return x.AppID
	}
	return 0
}

type GetUserListRsp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RetCode       uint32                 `protobuf:"varint,1,opt,name=retCode,proto3" json:"retCode,omitempty"`
	ErrMsg        string                 `protobuf:"bytes,2,opt,name=errMsg,proto3" json:"errMsg,omitempty"`
	UserID        []string               `protobuf:"bytes,3,rep,name=userID,proto3" json:"userID,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserListRsp) Reset() {
	*x = GetUserListRsp{}
	mi := &file_im_protobuf_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserListRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserListRsp) ProtoMessage() {}

func (x *GetUserListRsp) ProtoReflect() protoreflect.Message {
	mi := &file_im_protobuf_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserListRsp.ProtoReflect.Descriptor instead.
func (*GetUserListRsp) Descriptor() ([]byte, []int) {
	return file_im_protobuf_proto_rawDescGZIP(), []int{7}
}

func (x *GetUserListRsp) GetRetCode() uint32 {
	if x != nil {
		return x.RetCode
	}
	return 0
}

func (x *GetUserListRsp) GetErrMsg() string {
	if x != nil {
		return x.ErrMsg
	}
	return ""
}

func (x *GetUserListRsp) GetUserID() []string {
	if x != nil {
		return x.UserID
	}
	return nil
}

var File_im_protobuf_proto protoreflect.FileDescriptor

const file_im_protobuf_proto_rawDesc = "" +
	"\n" +
	"\x11im_protobuf.proto\x12\bprotobuf\"C\n" +
	"\x13QueryUsersOnlineReq\x12\x14\n" +
	"\x05appID\x18\x01 \x01(\rR\x05appID\x12\x16\n" +
	"\x06userID\x18\x02 \x01(\tR\x06userID\"_\n" +
	"\x13QueryUsersOnlineRsp\x12\x18\n" +
	"\aretCode\x18\x01 \x01(\rR\aretCode\x12\x16\n" +
	"\x06errMsg\x18\x02 \x01(\tR\x06errMsg\x12\x16\n" +
	"\x06online\x18\x03 \x01(\bR\x06online\"\xca\x01\n" +
	"\n" +
	"SendMsgReq\x12\x10\n" +
	"\x03seq\x18\x01 \x01(\tR\x03seq\x12\x14\n" +
	"\x05appID\x18\x02 \x01(\rR\x05appID\x12\x1e\n" +
	"\n" +
	"fromUserId\x18\x03 \x01(\tR\n" +
	"fromUserId\x12\x10\n" +
	"\x03cms\x18\x04 \x01(\tR\x03cms\x12\x12\n" +
	"\x04type\x18\x05 \x01(\tR\x04type\x12\x10\n" +
	"\x03msg\x18\x06 \x01(\tR\x03msg\x12\x18\n" +
	"\aisLocal\x18\a \x01(\bR\aisLocal\x12\"\n" +
	"\ftargetUserId\x18\b \x01(\tR\ftargetUserId\"\\\n" +
	"\n" +
	"SendMsgRsp\x12\x18\n" +
	"\aretCode\x18\x01 \x01(\rR\aretCode\x12\x16\n" +
	"\x06errMsg\x18\x02 \x01(\tR\x06errMsg\x12\x1c\n" +
	"\tsendMsgID\x18\x03 \x01(\tR\tsendMsgID\"\x87\x01\n" +
	"\rSendMsgAllReq\x12\x10\n" +
	"\x03seq\x18\x01 \x01(\tR\x03seq\x12\x14\n" +
	"\x05appID\x18\x02 \x01(\rR\x05appID\x12\x16\n" +
	"\x06userID\x18\x03 \x01(\tR\x06userID\x12\x10\n" +
	"\x03cms\x18\x04 \x01(\tR\x03cms\x12\x12\n" +
	"\x04type\x18\x05 \x01(\tR\x04type\x12\x10\n" +
	"\x03msg\x18\x06 \x01(\tR\x03msg\"_\n" +
	"\rSendMsgAllRsp\x12\x18\n" +
	"\aretCode\x18\x01 \x01(\rR\aretCode\x12\x16\n" +
	"\x06errMsg\x18\x02 \x01(\tR\x06errMsg\x12\x1c\n" +
	"\tsendMsgID\x18\x03 \x01(\tR\tsendMsgID\"&\n" +
	"\x0eGetUserListReq\x12\x14\n" +
	"\x05appID\x18\x01 \x01(\rR\x05appID\"Z\n" +
	"\x0eGetUserListRsp\x12\x18\n" +
	"\aretCode\x18\x01 \x01(\rR\aretCode\x12\x16\n" +
	"\x06errMsg\x18\x02 \x01(\tR\x06errMsg\x12\x16\n" +
	"\x06userID\x18\x03 \x03(\tR\x06userID2\x9f\x02\n" +
	"\tAccServer\x12R\n" +
	"\x10QueryUsersOnline\x12\x1d.protobuf.QueryUsersOnlineReq\x1a\x1d.protobuf.QueryUsersOnlineRsp\"\x00\x127\n" +
	"\aSendMsg\x12\x14.protobuf.SendMsgReq\x1a\x14.protobuf.SendMsgRsp\"\x00\x12@\n" +
	"\n" +
	"SendMsgAll\x12\x17.protobuf.SendMsgAllReq\x1a\x17.protobuf.SendMsgAllRsp\"\x00\x12C\n" +
	"\vGetUserList\x12\x18.protobuf.GetUserListReq\x1a\x18.protobuf.GetUserListRsp\"\x00B9\n" +
	"\x19io.grpc.examples.protobufB\rProtobufProtoP\x01Z\v../protobufb\x06proto3"

var (
	file_im_protobuf_proto_rawDescOnce sync.Once
	file_im_protobuf_proto_rawDescData []byte
)

func file_im_protobuf_proto_rawDescGZIP() []byte {
	file_im_protobuf_proto_rawDescOnce.Do(func() {
		file_im_protobuf_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_im_protobuf_proto_rawDesc), len(file_im_protobuf_proto_rawDesc)))
	})
	return file_im_protobuf_proto_rawDescData
}

var file_im_protobuf_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_im_protobuf_proto_goTypes = []any{
	(*QueryUsersOnlineReq)(nil), // 0: protobuf.QueryUsersOnlineReq
	(*QueryUsersOnlineRsp)(nil), // 1: protobuf.QueryUsersOnlineRsp
	(*SendMsgReq)(nil),          // 2: protobuf.SendMsgReq
	(*SendMsgRsp)(nil),          // 3: protobuf.SendMsgRsp
	(*SendMsgAllReq)(nil),       // 4: protobuf.SendMsgAllReq
	(*SendMsgAllRsp)(nil),       // 5: protobuf.SendMsgAllRsp
	(*GetUserListReq)(nil),      // 6: protobuf.GetUserListReq
	(*GetUserListRsp)(nil),      // 7: protobuf.GetUserListRsp
}
var file_im_protobuf_proto_depIdxs = []int32{
	0, // 0: protobuf.AccServer.QueryUsersOnline:input_type -> protobuf.QueryUsersOnlineReq
	2, // 1: protobuf.AccServer.SendMsg:input_type -> protobuf.SendMsgReq
	4, // 2: protobuf.AccServer.SendMsgAll:input_type -> protobuf.SendMsgAllReq
	6, // 3: protobuf.AccServer.GetUserList:input_type -> protobuf.GetUserListReq
	1, // 4: protobuf.AccServer.QueryUsersOnline:output_type -> protobuf.QueryUsersOnlineRsp
	3, // 5: protobuf.AccServer.SendMsg:output_type -> protobuf.SendMsgRsp
	5, // 6: protobuf.AccServer.SendMsgAll:output_type -> protobuf.SendMsgAllRsp
	7, // 7: protobuf.AccServer.GetUserList:output_type -> protobuf.GetUserListRsp
	4, // [4:8] is the sub-list for method output_type
	0, // [0:4] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_im_protobuf_proto_init() }
func file_im_protobuf_proto_init() {
	if File_im_protobuf_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_im_protobuf_proto_rawDesc), len(file_im_protobuf_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_im_protobuf_proto_goTypes,
		DependencyIndexes: file_im_protobuf_proto_depIdxs,
		MessageInfos:      file_im_protobuf_proto_msgTypes,
	}.Build()
	File_im_protobuf_proto = out.File
	file_im_protobuf_proto_goTypes = nil
	file_im_protobuf_proto_depIdxs = nil
}
